backend:
  name: github
  repo: mrohmer/carrera-standings
  branch: master

media_folder: "static/uploads"

collections:
  - name: 'cup'
    label: 'Cup'
    folder: 'cups'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - label: 'Titel'
        name: 'title'
      - label: "Datum"
        name: "date"
        widget: "datetime"

